name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli --upgrade

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init ${{ secrets.EB_APPLICATION_NAME }} --platform node.js --region ${{ secrets.AWS_REGION }}
          eb use ${{ secrets.EB_ENV_NAME }}
          eb deploy
